import {
  CheckSquare,
  StickyNote,
  Target,
  Timer,
  Bookmark,
  Goal,
  DollarSign,
  Clock,
  Kanban,
  BookOpen,
  Users,
  Book,
  Lightbulb,
  Calendar,
  CreditCard,
  Film,
  Code,
  ChefHat,
  Dumbbell,
  Smile,
  Brain,
  Gift,
  Car,
  Ribbon,
  KeyRound,
  ArrowRightLeft,
  Hourglass,
  Dices,
  Link,
  Quote,
  Cake,
  Calculator,
  Palette,
  Wallet,
  GraduationCap,
  Heart,
  Package,
  FileText,
  Braces,
  FileSearch,
  Pill,
  PawPrint,
  Leaf,
  QrCode,
  PiggyBank,
  Moon,
  Plane,
  Droplets,
  CloudSun,
  Type,
  FileCode2,
  Hash,
  Binary,
  Paintbrush,
  Square,
  Receipt,
  Banknote,
  Scale,
  Flame,
  Globe,
  History,
  Watch,
  TerminalSquare,
  Key,
  FileJson,
  Shield,
  Tags,
  CircleDot,
  ListChecks,
  Sparkles,
  TrendingUp,
  ClipboardList,
  Utensils,
  ShoppingCart,
  CalendarDays,
  ShieldCheck,
  FolderOpen,
  Ruler,
  CalendarRange,
  RotateCw,
  BookMarked,
  FileSignature,
  Vote,
  Grid3X3,
  HelpCircle,
  Mail,
  MapPin,
  Wifi,
  Radio,
  Ratio,
  Activity,
  Home,
  Gamepad2,
} from "lucide-react"
import type { NavGroup } from "@/types"

export const navGroups: NavGroup[] = [
  {
    title: "Productivity",
    icon: CheckSquare,
    items: [
      { title: "Tasks", href: "/tasks", icon: CheckSquare },
      { title: "Notes", href: "/notes", icon: StickyNote },
      { title: "Habits", href: "/habits", icon: Target },
      { title: "Goals", href: "/goals", icon: Goal },
      { title: "Pomodoro", href: "/pomodoro", icon: Timer },
      { title: "Kanban", href: "/kanban", icon: Kanban },
      { title: "Time Tracker", href: "/time", icon: Clock },
      { title: "Calendar", href: "/calendar", icon: Calendar },
      { title: "Journal", href: "/journal", icon: BookOpen },
      { title: "Ideas", href: "/ideas", icon: Lightbulb },
      { title: "Bookmarks", href: "/bookmarks", icon: Bookmark },
      { title: "Links", href: "/links", icon: Link },
    ],
  },
  {
    title: "Finance",
    icon: DollarSign,
    items: [
      { title: "Finances", href: "/finances", icon: DollarSign },
      { title: "Bills", href: "/bills", icon: Receipt },
      { title: "Debts", href: "/debts", icon: Wallet },
      { title: "Savings", href: "/savings", icon: PiggyBank },
      { title: "Net Worth", href: "/networth", icon: TrendingUp },
      { title: "Subscriptions", href: "/subscriptions", icon: CreditCard },
      { title: "Invoices", href: "/invoices", icon: FileText },
      { title: "Tip Calculator", href: "/tip", icon: Receipt },
      { title: "Loan Calculator", href: "/loan", icon: Banknote },
      { title: "Salary Converter", href: "/salary", icon: Banknote },
      { title: "Meeting Cost", href: "/meetingcost", icon: DollarSign },
    ],
  },
  {
    title: "Health & Fitness",
    icon: Activity,
    items: [
      { title: "Workouts", href: "/workouts", icon: Dumbbell },
      { title: "Mood", href: "/mood", icon: Smile },
      { title: "Sleep", href: "/sleep", icon: Moon },
      { title: "Water", href: "/water", icon: Droplets },
      { title: "Medications", href: "/medications", icon: Pill },
      { title: "BMI Calculator", href: "/bmi", icon: Scale },
      { title: "Calories", href: "/calories", icon: Flame },
      { title: "Measurements", href: "/measurements", icon: Ruler },
    ],
  },
  {
    title: "Home & Life",
    icon: Home,
    items: [
      { title: "Contacts", href: "/contacts", icon: Users },
      { title: "Birthdays", href: "/birthdays", icon: Cake },
      { title: "Recipes", href: "/recipes", icon: ChefHat },
      { title: "Meals", href: "/meals", icon: Utensils },
      { title: "Grocery", href: "/grocery", icon: ShoppingCart },
      { title: "Chores", href: "/chores", icon: ClipboardList },
      { title: "Inventory", href: "/inventory", icon: Package },
      { title: "Pets", href: "/pets", icon: PawPrint },
      { title: "Plants", href: "/plants", icon: Leaf },
      { title: "Vehicles", href: "/vehicles", icon: Car },
      { title: "Horses", href: "/horses", icon: Ribbon },
      { title: "Warranty", href: "/warranty", icon: ShieldCheck },
      { title: "Documents", href: "/documents", icon: FolderOpen },
      { title: "Parking", href: "/parking", icon: MapPin },
    ],
  },
  {
    title: "Learning",
    icon: GraduationCap,
    items: [
      { title: "Flashcards", href: "/flashcards", icon: Brain },
      { title: "Reading", href: "/reading", icon: Book },
      { title: "Grades", href: "/grades", icon: GraduationCap },
      { title: "Assignments", href: "/assignments", icon: BookMarked },
      { title: "Citations", href: "/citations", icon: FileSignature },
      { title: "Quotes", href: "/quotes", icon: Quote },
    ],
  },
  {
    title: "Entertainment",
    icon: Film,
    items: [
      { title: "Watchlist", href: "/watchlist", icon: Film },
      { title: "Wishlist", href: "/wishlist", icon: Gift },
      { title: "Bucket List", href: "/bucket", icon: ListChecks },
      { title: "Travel", href: "/travel", icon: Plane },
    ],
  },
  {
    title: "Planning",
    icon: CalendarDays,
    items: [
      { title: "Events", href: "/events", icon: CalendarDays },
      { title: "Schedule", href: "/schedule", icon: CalendarRange },
      { title: "Routines", href: "/routines", icon: RotateCw },
      { title: "Countdowns", href: "/countdowns", icon: Hourglass },
      { title: "RSVP", href: "/rsvp", icon: Mail },
      { title: "Pros/Cons", href: "/proscons", icon: Scale },
    ],
  },
  {
    title: "Mindfulness",
    icon: Heart,
    items: [
      { title: "Gratitude", href: "/gratitude", icon: Heart },
      { title: "Affirmations", href: "/affirmations", icon: Sparkles },
    ],
  },
  {
    title: "Dev Tools",
    icon: Code,
    items: [
      { title: "JSON", href: "/json", icon: Braces },
      { title: "Regex", href: "/regex", icon: Code },
      { title: "Snippets", href: "/snippets", icon: Code },
      { title: "Base64", href: "/base64", icon: Binary },
      { title: "Hash", href: "/hash", icon: Hash },
      { title: "UUID", href: "/uuid", icon: Hash },
      { title: "JWT Decoder", href: "/jwt", icon: Key },
      { title: "CSV ↔ JSON", href: "/csv", icon: FileJson },
      { title: "Cron Builder", href: "/cron", icon: TerminalSquare },
      { title: "Chmod", href: "/chmod", icon: Shield },
      { title: "Diff", href: "/diff", icon: FileCode2 },
      { title: "Markdown", href: "/markdown", icon: FileSearch },
    ],
  },
  {
    title: "Text Tools",
    icon: Type,
    items: [
      { title: "Lorem Ipsum", href: "/lorem", icon: Type },
      { title: "Word Counter", href: "/counter", icon: Type },
      { title: "Case Converter", href: "/case", icon: Type },
      { title: "Morse Code", href: "/morse", icon: Radio },
      { title: "Binary", href: "/binary", icon: Binary },
    ],
  },
  {
    title: "Design Tools",
    icon: Palette,
    items: [
      { title: "Colors", href: "/colors", icon: Palette },
      { title: "Gradient", href: "/gradient", icon: Paintbrush },
      { title: "Shadows", href: "/shadows", icon: Square },
      { title: "QR Code", href: "/qrcode", icon: QrCode },
      { title: "Meta Tags", href: "/meta", icon: Tags },
      { title: "Aspect Ratio", href: "/aspect", icon: Ratio },
    ],
  },
  {
    title: "Calculators",
    icon: Calculator,
    items: [
      { title: "Calculator", href: "/calculator", icon: Calculator },
      { title: "Converter", href: "/converter", icon: ArrowRightLeft },
      { title: "Timezone", href: "/timezone", icon: Globe },
      { title: "Epoch", href: "/epoch", icon: History },
      { title: "Stopwatch", href: "/stopwatch", icon: Watch },
    ],
  },
  {
    title: "Security",
    icon: KeyRound,
    items: [
      { title: "Passwords", href: "/passwords", icon: KeyRound },
      { title: "WiFi Card", href: "/wifi", icon: Wifi },
    ],
  },
  {
    title: "Fun & Games",
    icon: Gamepad2,
    items: [
      { title: "Dice", href: "/dice", icon: Dices },
      { title: "Wheel Spinner", href: "/wheel", icon: CircleDot },
      { title: "Bingo", href: "/bingo", icon: Grid3X3 },
      { title: "Trivia", href: "/trivia", icon: HelpCircle },
      { title: "Polls", href: "/polls", icon: Vote },
      { title: "Secret Santa", href: "/secretsanta", icon: Gift },
    ],
  },
  {
    title: "Weather",
    icon: CloudSun,
    items: [
      { title: "Weather", href: "/weather", icon: CloudSun },
    ],
  },
]

// Flat list for backwards compatibility
export const mainNavItems = navGroups.flatMap(group => group.items)
